# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_zoomerjoin_wrappers", use_symbols = TRUE, package_name = "zoomerjoin")

#' @docType package
#' @usage NULL
#' @useDynLib zoomerjoin, .registration = TRUE
NULL

rust_lsh_join <- function(left_string_r, right_string_r, ngram_width, n_bands, band_size, threshold) .Call(wrap__rust_lsh_join, left_string_r, right_string_r, ngram_width, n_bands, band_size, threshold)

rust_jaccard_similarity <- function(left_string_r, right_string_r, ngram_width) .Call(wrap__rust_jaccard_similarity, left_string_r, right_string_r, ngram_width)

#' @export
em_link <- function(comparison_robj, params_given_match, params_given_not_match, lambda, tol) .Call(wrap__em_link, comparison_robj, params_given_match, params_given_not_match, lambda, tol)

